# Generated by Django 4.1.4 on 2022-12-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_tag_pedido_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tags',
        ),
        migrations.AddField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(to='contas.tag'),
        ),
    ]
