# Generated by Django 4.1.4 on 2022-12-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_remove_pedido_tags_produto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
